[package]
name = "monkeyframe_rust_grouper_v2"
version = "0.1.0"
edition = "2021"

[lib]
name = "monkeyframe_rust_grouper_v2"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.0", features = ["extension-module"] }
arrow = { version = "34.0.0", features = ["pyarrow"] }
